version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "✅ No dependencies to install for static frontend"

  build:
    commands:
      - echo "📁 Listing current directory contents..."
      - ls -al || echo "⚠️ No files found in build root"
      - echo "🚀 Starting S3 sync to windy-artifact-bucket..."
      - |
        if aws s3 ls "s3://windy-artifact-bucket" >/dev/null 2>&1; then
          aws s3 sync . s3://windy-artifact-bucket/ --delete
          echo "✅ Deployment complete"
        else
          echo "❌ Bucket not found or access denied: windy-artifact-bucket"
          exit 1
        fi

artifacts:
  files:
    - '**/*'
