version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "✅ No dependencies to install for static frontend"

  build:
    commands:
      - echo "🚀 Starting S3 sync"
      - aws s3 sync . s3://windy-artifact-bucket/ --delete
      - echo "✅ Deployment complete"

artifacts:
  files:
    - '**/*'
